import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const root=path.resolve(import.meta.dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const inline=html.match(/<script>\s*([\s\S]*?)<\/script>/)?.[1];
if(!inline||!html.includes('<script src="analysis.js?v=4.2.2"></script>')||!html.includes('<script src="prediction-history.js?v=1"></script>')||!html.includes('<script src="measurement-guidance.js?v=1"></script>'))throw new Error('Required versioned scripts missing');
new vm.Script(inline,{filename:'index-inline.js'});
new vm.Script(fs.readFileSync(path.join(root,'analysis.js'),'utf8'),{filename:'analysis.js'});
new vm.Script(fs.readFileSync(path.join(root,'prediction-history.js'),'utf8'),{filename:'prediction-history.js'});
new vm.Script(fs.readFileSync(path.join(root,'measurement-guidance.js'),'utf8'),{filename:'measurement-guidance.js'});
new vm.Script(fs.readFileSync(path.join(root,'sw.js'),'utf8'),{filename:'sw.js'});
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
if(manifest.start_url!=='./'||manifest.scope!=='./'||!manifest.icons?.some(icon=>icon.src==='./icon.svg'))throw new Error('Invalid local PWA manifest');
const dist=path.join(root,'dist');fs.mkdirSync(dist,{recursive:true});
for(const name of ['index.html','analysis.js','prediction-history.js','measurement-guidance.js','sw.js','manifest.webmanifest','icon.svg'])fs.copyFileSync(path.join(root,name),path.join(dist,name));
console.log('Static production build:',dist);
